# GoReleaser configuration for NetCrate
# This configuration enables multi-platform builds and GitHub releases

before:
  hooks:
    # Clean up any previous builds
    - go mod tidy
    - go generate ./...

builds:
  # Main NetCrate binary
  - id: netcrate
    main: ./cmd/netcrate
    binary: netcrate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Skip unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/netcrate/netcrate/internal/version.Version={{.Version}}
      - -X github.com/netcrate/netcrate/internal/version.Commit={{.Commit}}
      - -X github.com/netcrate/netcrate/internal/version.Date={{.Date}}
      - -X github.com/netcrate/netcrate/internal/version.BuiltBy=goreleaser

  # Simple version for testing
  - id: netcrate-simple
    main: ./cmd/netcrate-simple
    binary: netcrate-simple
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**/*
      - templates/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Security Updates'
      regexp: "^.*sec[(\\w)]*:+.*$"
      order: 2
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 3
    - title: 'Documentation Updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 4
    - title: 'Other Changes'
      order: 999

# GitHub release configuration
release:
  github:
    owner: netcrate
    name: netcrate
  draft: false
  prerelease: auto
  name_template: "NetCrate {{.Version}}"

# Homebrew tap formula generation
brews:
  - name: netcrate
    ids:
      - netcrate
    tap:
      owner: netcrate
      name: homebrew-tap
      branch: main
    homepage: https://github.com/netcrate/netcrate
    description: "Network security testing toolkit with compliance controls"
    license: "MIT"
    folder: Formula
    install: |
      bin.install "netcrate"
    test: |
      system "#{bin}/netcrate", "version"

# Universal binaries for macOS (combines amd64 and arm64)
universal_binaries:
  - id: netcrate-universal
    ids:
      - netcrate
    name_template: 'netcrate'
    replace: false

# Package validation
env_files:
  github_token: ~/.config/goreleaser/github_token