# GoReleaser configuration for NetCrate
version: 2

project_name: netcrate

builds:
  - main: ./cmd/netcrate-simple
    binary: netcrate
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/**/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  use: git
  filters:
    exclude:
      - '^chore:'
      - '^test:'
      - '^docs:'
      - '^ci:'

release:
  draft: false
  prerelease: auto
  name_template: "NetCrate {{.Version}}"
  header: |
    ## NetCrate {{.Version}}
    
    Professional network security testing toolkit with built-in compliance controls.

brews:
  - name: netcrate
    repository:
      owner: Ludan-daye
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/Ludan-daye/Atomic-Chain-Network-Test"
    description: "Network security testing toolkit with compliance controls"
    license: "MIT"
    install: |
      bin.install "netcrate"
    test: |
      system "#{bin}/netcrate", "--help"